<?php

namespace AppBundle\Entity;

/**
 * Modelo1007Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Modelo1007Repository extends \Doctrine\ORM\EntityRepository
{

    public function modelosConsolidado($estado, $id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo1007","m")
            ->innerJoin("m.modelo", "u");
        if($id != -1){
            $query->innerJoin("u.usuario", "us")
                ->innerJoin("us.empresa", "e");
        }
        $query->where("u.estado =:estado");
        if ($id !=-1) {
            $query->andWhere("e.id =:id")
                ->setParameter("id",$id);
        }
        $query->setParameter("estado",$estado);
            return $query->getQuery()->getResult();
    }

    public function updateModelos(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $q = $qb->update("AppBundle:Modelo", "m")
            ->set('m.estado', '?1')
            ->where('m.estado = 2')
            ->setParameter(1, 3)
            ->getQuery();
        $p = $q->execute();
    }

}
