<?php

namespace AppBundle\Entity;

/**
 * ModeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloRepository extends \Doctrine\ORM\EntityRepository
{
    public function modeloAbierto($tipo, $id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo","m")
            ->innerJoin("m.usuario", "u")
            ->innerJoin("u.empresa", "e")
            ->where("m.estado =:estado AND m.tipo =:tipo AND e.id =:id")
            ->setParameter("estado",1)
            ->setParameter("tipo",$tipo)
            ->setParameter("id",$id)
            ->getQuery()
            ->getResult();

        return $query;
    }

    public function countModelos($estado){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("COUNT(e)")
            ->from("AppBundle:Modelo","e")
            ->where("e.estado =:estado")
            ->setParameter("estado",$estado)
            ->getQuery()
            ->getSingleScalarResult();

        return $query;
    }

    public function modelos($tipo, $id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo","m")
            ->innerJoin("m.usuario", "u")
            ->innerJoin("u.empresa", "e")
            ->where("m.tipo =:tipo AND e.id =:id")
            ->setParameter("tipo",$tipo)
            ->setParameter("id",$id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
