<?php

namespace AppBundle\Entity;

/**
 * Modelo101BRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Modelo101BRepository extends \Doctrine\ORM\EntityRepository
{
    public function modelos($id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo101b","m")
            ->innerJoin("m.usuario", "u")
            ->innerJoin("u.empresa", "e")
            ->where("e.id =:id")
            ->setParameter("id",$id)
            ->getQuery()
            ->getResult();

        return $query;
    }
    public function countModelosB($estado){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("COUNT(e)")
            ->from("AppBundle:Modelo101B","e")
            ->where("e.estado =:estado")
            ->setParameter("estado",$estado)
            ->getQuery()
            ->getSingleScalarResult();

        return $query;
    }

    public function updateModelosB(){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $q = $qb->update("AppBundle:Modelo101B", "m")
            ->set('m.estado', '?1')
            ->where('m.estado = 2')
            ->setParameter(1, 3)
            ->getQuery();
        $p = $q->execute();
    }

    public function modelosConsolidado($estado, $id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo101b","m");
        if($id != -1){
            $query->innerJoin("m.usuario", "u")
                ->innerJoin("u.empresa", "e");
        }
        $query->where("m.estado =:estado");
        if ($id !=-1) {
            $query->andWhere("e.id =:id")
                ->setParameter("id",$id);
        }
        $query->setParameter("estado",$estado);
        return $query->getQuery()->getResult();
    }

    public function modeloAbierto($id){
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select("m")
            ->from("AppBundle:Modelo101b","m")
            ->innerJoin("m.usuario", "u")
            ->innerJoin("u.empresa", "e")
            ->where("m.estado =:estado AND e.id =:id")
            ->setParameter("estado",1)
            ->setParameter("id",$id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
